FROM langchain/langchain:latest

EXPOSE 8080

ENV S_ENV=DEV

COPY requirements/base.txt .
RUN python -m pip install --upgrade pip && \
    python -m pip install -r base.txt

WORKDIR /app
COPY . /app

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

WORKDIR /app/app


CMD ["gunicorn", "--bind", "0.0.0.0:8080", "-k", "uvicorn.workers.UvicornWorker", "main:app"]
